[tool]
[tool.poetry]
name = "jwskate"
version = "0.1.0"
homepage = "https://github.com/guillp/jwskate"
description = "A Pythonic implementation of Json Web Signature, Keys, Algorithms, Tokens and Encryption (RFC7514 to 7519), on top of the `cryptography` module."
authors = ["Guillaume Pujol <guill.p.linux@gmail.com>"]
readme = "README.md"
license =  "MIT"
classifiers=[
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
]
packages = [
    { include = "jwskate" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
cryptography = "^3.4.8"
binapy = "^0.4.0"

[tool.poetry.dev-dependencies]
black  = "^22.1.0"
coverage = "^6.3.1"
flake8  = "^4.0.1"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.3"
isort  = "^5.10.1"
jwcrypto = "^1.0"
livereload = "^2.6.3"
mypy = "^0.931"
mkdocs  = "^1.2.3"
mkdocstrings = "^0.18"
mkdocs-autorefs = "^0.3.0"
mkdocs-include-markdown-plugin  = "^3.2.3"
mkdocs-material  = "^8.2.1"
mkdocs-material-extensions  = "^1.0.1"
pip  = "^22.0.2"
pre-commit = "^2.12.0"
pytest  = "^7.0.1"
pytest-cov  = "^3.0.0"
pytest-mypy = "^0.9.1"
requests-mock = "^1.9.3"
toml = "^0.10.2"
tox  = "^3.20.1"
twine  = "^3.8.0"
types-requests = "^2.27.10"
types-cryptography = "^3.3.15"
virtualenv  = "^20.13.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
strict = true
implicit_reexport = true
pretty = true
show_error_context = true
show_column_numbers = true
show_error_codes = true
warn_unused_configs = true
warn_unused_ignores = true
warn_redundant_casts = true
